spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        
# JWT Configuration for testing
jwt:
  secret: this-is-a-test-secret-key-must-be-at-least-256-bits-long-for-hs256
  expiration: 3600000
  refresh-expiration: 604800000

# OAuth Configuration for testing (mock values)
oauth:
  google:
    client-id: test-google-client-id
  apple:
    client-id: test-apple-client-id

# Disable Redis for testing
spring.data.redis.repositories.enabled: false

# Application specific
app:
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:5173

logging:
  level:
    com.oddiya: DEBUG
    org.springframework.security: DEBUG
    
server:
  port: 8080