name: Deployment Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  
env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
  JAVA_VERSION: '21'
  JAVA_DISTRIBUTION: 'temurin'

jobs:
  build-for-deployment:
    name: Build for Deployment
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: gradle
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
      
      - name: Build deployment JAR
        run: ./gradlew buildForDeployment --no-daemon --stacktrace -PskipQualityChecks=true
      
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment-jar
          path: build/libs/oddiya.jar
          retention-days: 7
          if-no-files-found: error
      
      - name: Display build info
        run: |
          echo "## 🚀 Deployment Build Complete" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "**Commit:** \`${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**JAR:** oddiya.jar" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### ✅ Ready for Deployment" >> $GITHUB_STEP_SUMMARY
          echo "The application JAR has been built successfully and is ready for deployment." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Download the artifact from the Actions tab to deploy." >> $GITHUB_STEP_SUMMARY